let dados = [    
{
        titulo : "SÃO PAULO X PONTA PORÃ - 14:30",
        descricao : "SAO PAULO - SP ( TERMINAL RODOVIARIO BARRA FUNDA ) 14:30 | JUNDIAI - SP ( TERMINAL RODOVIARIO ) 15:30 | PADRAO CAMPINAS - SP ( TERMINAL RODOVIARIO ) 16:15  | AMERICANA - SP ( TERMINAL RODOVIARIO ) 17:00 |PIRACICABA - SP ( TERMINAL RODOVIARIO ) 17:45 | GRAAL MARISTELA – SP | OURINHOS - SP ( TERMINAL RODOVIARIO ) 22:05 | ASSIS - SP ( TERMINAL RODOVIARIO ) 23:05 | PRESIDENTE PRUDENTE - SP ( TERMINAL RODOVIARIO ) 01:00 | BATAGUASSU - MS ( TERMINAL RODOVIARIO ) 02:15 | NOVA ANDRADINA-NOVA CASA VERDE - MS ( POSTO GABRIELLY ) 03:45 | NOVA ALVORADA DO SUL - MS ( TERMINAL RODOVIARIO ) 05:00 | RIO BRILHANTE - MS ( TERMINAL RODOVIARIO ) 06:20 | DOURADOS - MS ( TERMINAL RODOVIARIO ) 07:20 | PONTA PORA - MS ( TERMINAL RODOVIARIO ) 09:20",
        link : "https://wa.me/5567999718063",
        tags : "SÃO PAULO X PONTA PORÃ"
    },
    {
        titulo : "SÃO PAULO X PONTA PORÃ – 18:00",
        descricao : "SAO PAULO - SP ( TERMINAL RODOVIARIO BARRA FUNDA ) 18:00 | GRAAL MARISTELA - SP 20:45 | PRESIDENTE PRUDENTE - SP ( TERMINAL RODOVIARIO ) 01:45 | NOVA ANDRADINA-NOVA CASA VERDE - MS ( POSTO GABRIELLY ) | RIO BRILHANTE - MS ( TERMINAL RODOVIARIO ) 06:05 | DOURADOS - MS ( TERMINAL RODOVIARIO ) 07:25 | PONTA PORA - MS ( TERMINAL RODOVIARIO ) 09:40",
        link : "https://wa.me/5567999718063",
        tags : "SÃO PAULO X PONTA PORÃ"
    },
    {
        titulo : "SÃO PAULO X PONTA PORÃ – 22:00",
        descricao : "SAO PAULO - SP ( TERMINAL RODOVIARIO BARRA FUNDA ) 22:00 | OSASCO - SP ( TERMINAL RODOVIARIO ) 22:30 | GRAAL PALOMA - SP 02:05 | PRESIDENTE PRUDENTE - SP ( TERMINAL RODOVIARIO ) 05:00 | BATAGUASSU - MS ( TERMINAL RODOVIARIO ) 05:55 | NOVA ANDRADINA-NOVA CASA VERDE - MS ( POSTO GABRIELLY ) 07:30 00:00 07:30 0 0 5 NOVA ALVORADA DO SUL - MS ( TERMINAL RODOVIARIO ) 09:00 | RIO BRILHANTE - MS ( TERMINAL RODOVIARIO ) 10:00 | DOURADOS - MS ( TERMINAL RODOVIARIO ) 11:05 | PONTA PORA - MS ( TERMINAL RODOVIARIO ) 13:05 ",
        link : "https://wa.me/5567999718063",
        tags : "SÃO PAULO X PONTA PORÃ"
    },
    {
        titulo : "SÃO PAULO X CAMPO GRANDE 16:00",
        descricao : "SAO PAULO - SP ( TERMINAL RODOVIARIO BARRA FUNDA ) 16:00 | PRESIDENTE PRUDENTE - SP ( TERMINAL RODOVIARIO ) 23:40 | BATAGUASSU - MS ( TERMINAL RODOVIARIO ) 00:55 | NOVA ANDRADINA-NOVA CASA VERDE - MS ( POSTO GABRIELLY ) 02:15 | NOVA ALVORADA DO SUL - MS ( TERMINAL RODOVIARIO ) 04:25 | CAMPO GRANDE - MS ( TERMINAL RODOVIARIO ) 06:00",
        link : "https://wa.me/5567999718063",
        tags : "SÃO PAULO X CAMPO GRANDE"
    },
    {
        titulo : "SÃO PAULO X CAMPO GRANDE 21:30",
        descricao : "SAO PAULO - SP ( TERMINAL RODOVIARIO BARRA FUNDA ) 21:30 | OSASCO - SP ( TERMINAL RODOVIARIO ) 22:00 | GRAAL MARISTELA - SP 00:35 | PRESIDENTE PRUDENTE - SP ( TERMINAL RODOVIARIO ) 05:20 | SANTO ANASTACIO - SP ( TERMINAL RODOVIARIO ) 06:30 | PRESIDENTE VENCESLAU - SP ( TERMINAL RODOVIARIO ) 07:05 | PRESIDENTE EPITACIO - SP ( TERMINAL RODOVIARIO ) 07:45 | BATAGUASSU - MS ( TERMINAL RODOVIARIO ) 07:30 | NOVA ANDRADINA-NOVA CASA VERDE - MS ( POSTO GABRIELLY ) 08:50 | NOVA ALVORADA DO SUL - MS ( TERMINAL RODOVIARIO ) 11:00 | CAMPO GRANDE - MS ( TERMINAL RODOVIARIO ) 12:35",
        link : "https://wa.me/5567999718063",
        tags : "SÃO PAULO X CAMPO GRANDE"
    },
    {
        titulo : "CAMPO GRANDE X SÃO PAULO 14:30",
        descricao : "CAMPO GRANDE - MS ( TERMINAL RODOVIARIO ) 14:30 | NOVA ALVORADA DO SUL - MS ( TERMINAL RODOVIARIO ) 16:00 | NOVA ANDRADINA-NOVA CASA VERDE - MS ( POSTO GABRIELLY ) 17:45 | BATAGUASSU - MS ( TERMINAL RODOVIARIO ) 19:25 | PRESIDENTE EPITACIO - SP ( TERMINAL RODOVIARIO ) 21:15 | PRESIDENTE PRUDENTE - SP ( TERMINAL RODOVIARIO ) 22:45 | GRAAL MARISTELA - SP 03:40 | OSASCO - SP ( TERMINAL RODOVIARIO ) 06:40 | SAO PAULO - SP ( TERMINAL RODOVIARIO BARRA FUNDA ) 07:15",
        link : "https://wa.me/5567999718063",
        tags : "CAMPO GRANDE X SÃO PAULO"
    },
    {
        titulo : "CAMPO GRANDE X SÃO PAULO 20:30",
        descricao : "CAMPO GRANDE - MS ( TERMINAL RODOVIARIO ) 20:30 | NOVA ALVORADA DO SUL - MS ( TERMINAL RODOVIARIO ) 22:00 | NOVA ANDRADINA-NOVA CASA VERDE - MS ( POSTO GABRIELLY ) 23:45 | BATAGUASSU - MS ( TERMINAL RODOVIARIO ) 01:25 | PRESIDENTE PRUDENTE - SP ( TERMINAL RODOVIARIO ) 04:05 | GRAAL MARISTELA - SP 09:00 | SAO PAULO - SP ( TERMINAL RODOVIARIO BARRA FUNDA ) 12:30",
        link : "https://wa.me/5567999718063",
        tags : "CAMPO GRANDE X SÃO PAULO"
    },
   {
        titulo : " CAMPO GRANDE X BRASILIA 14:45",
        descricao : "CAMPO GRANDE - MS ( TERMINAL RODOVIARIO ) 14:45 | BANDEIRANTES - MS ( TERMINAL RODOVIARIO ) 16:15 | CAMAPUÃ - MS ( TERMINAL RODOVIARIO ) 17:15 | CHAPADÃO DO SUL - MS ( TERMINAL RODOVIARIO )  | JATAI - GO ( TERMINAL RODOVIARIO ) 00:15 | RIO VERDE - GO ( TERMINAL RODOVIARIO ) 02:00 | GOIANIA - GO ( TERMINAL RODOVIARIO ) 05:50 | ANAPOLIS - GO ( TERMINAL RODOVIARIO ) 07:15 | BRASILIA - DF ( TERMINAL RODOVIARIO ) 09:15",
        link : "https://wa.me/5567999718063",
        tags : "CAMPO GRANDE X SÃO PAULO"
    },
    {
        titulo : "CAMPO GRANDE X BRASILIA 19:30",
        descricao : "CAMPO GRANDE - MS ( TERMINAL RODOVIARIO ) 19:30 | CAMPO GRANDE - MS (SAGITARIUS) 20:00 | CHAPADÃO DO SUL - MS ( TERMINAL RODOVIARIO ) 00:45 | JATAI - GO ( TERMINAL RODOVIARIO ) 03:50 | RIO VERDE - GO ( TERMINAL RODOVIARIO ) 05:30 | GOIANIA - GO ( TERMINAL RODOVIARIO ) 09:50 | BRASILIA - DF ( TERMINAL RODOVIARIO ) 13:30",
        link : "https://wa.me/5567999718063",
        tags : "CAMPO GRANDE X BRASILIA"
    },
    {
        titulo : "DOURADOS X CAMPO GRANDE 14:00",
        descricao : "DOURADOS - MS ( TERMINAL RODOVIARIO ) 14:00 | RIO BRILHANTE - MS ( TERMINAL RODOVIARIO ) 15:10 | NOVA ALVORADA DO SUL - MS ( TERMINAL RODOVIARIO ) 16:10 | ANHANDUI - MS ( TERMINAL RODOVIARIO ) 17:00 | CAMPO GRANDE - MS ( TERMINAL RODOVIARIO ) ",
        link : "https://wa.me/5567999718063",
        tags : "DOURADOS X CAMPO GRANDE"
    },
    {
        titulo : "PRESIDENTE PRUDENTE X BELO HORIZONTE 13:00",
        descricao : "PRESIDENTE PRUDENTE - SP ( TERMINAL RODOVIARIO ) 13:00 | ASSIS - SP ( TERMINAL RODOVIARIO ) 14:35 | MARILIA - SP ( TERMINAL RODOVIARIO ) 15:40 | BAURU - SP ( TERMINAL RODOVIARIO ) 17:15 | JAU - SP ( TERMINAL RODOVIARIO ) 18:55 | ARARAQUARA - SP ( TERMINAL RODOVIARIO ) 20:10 | SAO CARLOS - SP ( TERMINAL RODOVIARIO ) 20:55 | RIBEIRÃO PRETO - SP ( TERMINAL RODOVIARIO ) 22:40 | SAO SEBASTIAO DO PARAISO - MG ( TERMINAL RODOVIARIO ) 01:10 | PASSOS - MG ( TERMINAL RODOVIARIO ) 02:15 | PIUMHI - MG ( TERMINAL RODOVIARIO ) 03:50 | POSTO MAR DE MINAS - MG 04:55 | DIVINOPOLIS - MG ( TERMINAL RODOVIARIO ) 06:35 | ITAUNA - MG ( TERMINAL RODOVIARIO ) 07:30 | BETIM - MG ( TERMINAL RODOVIARIO ) 08:25 | BELO HORIZONTE - MG ( TERMINAL RODOVIARIO ) 09:10",
        link : "https://wa.me/5567999718063",
        tags : "PRESIDENTE PRUDENTE X BELO HORIZONTE"
    },
    {
        titulo : "CAMPO GRANDE X BELO HORIZONTE 20:00",
        descricao : "CAMPO GRANDE - MS ( TERMINAL RODOVIARIO ) 20:00 | NOVA ALVORADA DO SUL - MS ( TERMINAL RODOVIARIO ) 21:30 | NOVA ANDRADINA-NOVA CASA VERDE - MS ( POSTO GABRIELLY ) 23:15 | BATAGUASSU - MS ( TERMINAL RODOVIARIO ) 00:55 | PRESIDENTE PRUDENTE - SP ( TERMINAL RODOVIARIO ) 03:35 | ASSIS - SP ( TERMINAL RODOVIARIO ) 05:50 | MARILIA - SP ( TERMINAL RODOVIARIO ) 06:55 | BAURU - SP ( TERMINAL RODOVIARIO ) 08:35 | JAU - SP ( TERMINAL RODOVIARIO ) 10:20 | ARARAQUARA - SP ( TERMINAL RODOVIARIO ) 11:35 | SAO CARLOS - SP ( TERMINAL RODOVIARIO ) 12:25 | RIBEIRÃO PRETO - SP ( TERMINAL RODOVIARIO ) 14:05 | SAO SEBASTIAO DO PARAISO - MG ( TERMINAL RODOVIARIO ) 16:45 | PASSOS - MG ( TERMINAL RODOVIARIO ) 17:50 | PIUMHI - MG ( TERMINAL RODOVIARIO ) 19:30 | POSTO MAR DE MINAS - MG 20:35 | DIVINOPOLIS - MG ( TERMINAL RODOVIARIO ) 22:15 | BETIM - MG ( TERMINAL RODOVIARIO ) 23:45 | BELO HORIZONTE - MG ( TERMINAL RODOVIARIO ) 00:30",
        link : "https://wa.me/5567999718063",
        tags : "CAMPO GRANDE X BELO HORIZONTE"
    },
    {
        titulo : "CAMPO GRANDE X CUIABA 19:45",
        descricao : "CAMPO GRANDE - MS ( TERMINAL RODOVIARIO ) 19:45 | CAMPO GRANDE - MS (SAGITARIUS) 20:15 | SAO GABRIEL DO OESTE - MS ( TERMINAL RODOVIARIO ) 22:20 | RIO VERDE DE MATO GROSSO - MS ( TERMINAL RODOVIARIO ) 23:05 | COXIM - MS ( TERMINAL RODOVIARIO ) 00:25 | SONORA - MS ( TERMINAL RODOVIARIO ) 02:00 | RONDONOPOLIS - MT ( TERMINAL RODOVIARIO ) 03:55 | JACIARA - MT ( TERMINAL RODOVIARIO ) 05:30 | CUIABA (COXIPO) - MT 07:15 | CUIABA - MT ( TERMINAL RODOVIARIO ) 07:50",
        link : "https://wa.me/5567999718063",
        tags : "CAMPO GRANDE X CUIABA"
    },
    {
        titulo : "LONDRINA X CUIABA 21:00",
        descricao : "LONDRINA - PR ( TERMINAL RODOVIARIO ) 21:00 | ROLANDIA - PR ( TERMINAL RODOVIARIO ) 21:35 | PORECATU - PR ( TERMINAL RODOVIARIO ) 22:40 | PRESIDENTE PRUDENTE - SP ( TERMINAL RODOVIARIO ) 23:50 | PRESIDENTE EPITACIO - SP ( TERMINAL RODOVIARIO ) 01:30 | BATAGUASSU - MS ( TERMINAL RODOVIARIO ) 01:20 | NOVA ANDRADINA-NOVA CASA VERDE - MS ( POSTO GABRIELLY ) 03:00 | NOVA ALVORADA DO SUL - MS ( TERMINAL RODOVIARIO ) 05:15 | CAMPO GRANDE - MS ( TERMINAL RODOVIARIO ) 07:05 | CAMPO GRANDE - MS (SAGITARIUS) 08:05 | BANDEIRANTES - MS ( TERMINAL RODOVIARIO ) 09:20 |  SAO GABRIEL DO OESTE - MS ( TERMINAL RODOVIARIO ) 10:40 | RIO VERDE DE MATO GROSSO - MS ( TERMINAL RODOVIARIO ) 11:50 | COXIM - MS ( TERMINAL RODOVIARIO ) 12:55 | SONORA - MS ( TERMINAL RODOVIARIO ) 14:25 | RONDONOPOLIS - MT ( TERMINAL RODOVIARIO ) 16:10 | JACIARA - MT ( TERMINAL RODOVIARIO ) 17:15 | CUIABA (COXIPO) - MT 19:15 | CUIABA - MT ( TERMINAL RODOVIARIO ) 19:35",
        link : "https://wa.me/5567999718063",
        tags : "LONDRINA X CUIABA"
    },
    {
        titulo : " BRASILIA X CAMPO GRANDE 19:00",
        descricao : "BRASILIA - DF ( TERMINAL RODOVIARIO ) 19:00 | TAGUATINGA - DF ( TERMINAL RODOVIARIO ) 19:35 | ANAPOLIS - GO ( TERMINAL RODOVIARIO ) 22:10 | GOIANIA - GO ( TERMINAL RODOVIARIO ) 23:10 | ITUMBIARA - GO ( TERMINAL RODOVIARIO ) 02:40 | UBERLÂNDIA - MG ( TERMINAL RODOVIARIO ) 04:45 | PRATA - MG ( TERMINAL RODOVIARIO ) 06:15 | FRUTAL - MG ( TERMINAL RODOVIARIO ) 08:25 | FRONTEIRA - MG ( TERMINAL RODOVIARIO ) 09:20 | SAO JOSE DO RIO PRETO - SP ( TERMINAL RODOVIARIO ) 10:25 | BIRIGUI - SP ( TERMINAL RODOVIARIO ) 13:20 | ARACATUBA - SP ( TERMINAL RODOVIARIO ) 13:45 | TRES LAGOAS - MS ( TERMINAL RODOVIARIO ) 15:05 | AGUA CLARA - MS ( TERMINAL RODOVIARIO ) 17:50 | RIBAS DO RIO PARDO - MS ( TERMINAL RODOVIARIO ) 19:15 | CAMPO GRANDE - MS ( TERMINAL RODOVIARIO ) 20:50",
        link : "https://wa.me/5567999718063",
        tags : "BRASILIA X CAMPO GRANDE"
    },
    {
        titulo : "BRASILIA X CAMPO GRANDE 17:30",
        descricao : "BRASILIA - DF ( TERMINAL RODOVIARIO ) 17:30 | GOIANIA - GO ( TERMINAL RODOVIARIO ) 21:30 | RIO VERDE - GO ( TERMINAL RODOVIARIO ) 01:05 | JATAI - GO ( TERMINAL RODOVIARIO ) 02:35 | CHAPADÃO DO SUL - MS ( TERMINAL RODOVIARIO ) 04:35 | CAMPO GRANDE - MS ( TERMINAL RODOVIARIO ) 09:35",
        link : "https://wa.me/5567999718063",
        tags : "BRASILIA X CAMPO GRANDE"
    },
    {
        titulo : "BRASILIA X CAMPO GRANDE 13:00",
        descricao : "BRASILIA - DF ( TERMINAL RODOVIARIO ) 13:00 | TAGUATINGA - DF ( TERMINAL RODOVIARIO ) 13:35 | ANAPOLIS - GO ( TERMINAL RODOVIARIO ) 15:20 | GOIANIA - GO ( TERMINAL RODOVIARIO ) 16:50 | GOIANIA - GO (TERMINAL CAMPINAS) 17:10 | RIO VERDE - GO ( TERMINAL RODOVIARIO ) 21:10 | JATAI - GO ( TERMINAL RODOVIARIO ) 22:30 | CHAPADÃO DO SUL - MS ( TERMINAL RODOVIARIO ) 00:45 | CAMAPUÃ - MS ( TERMINAL RODOVIARIO ) 03:20 | CAMPO GRANDE - MS ( TERMINAL RODOVIARIO ) 06:00",
        link : "https://wa.me/5567999718063",
        tags : "BRASILIA X CAMPO GRANDE"
    },
    {
        titulo : "BRASILIA X CAMPO GRANDE 08:30",
        descricao : "TAGUATINGA - DF ( TERMINAL RODOVIARIO ) 08:30 | BRASILIA - DF ( TERMINAL RODOVIARIO ) 09:00 | VALPARAÍSO DE GOIÁS - GO 10:05 | CRISTALINA - GO ( TERMINAL RODOVIARIO ) 12:05 | CATALAO - GO ( TERMINAL RODOVIARIO ) 14:25 | ARAGUARI - MG ( TERMINAL RODOVIARIO ) 15:45 | UBERLÂNDIA - MG ( TERMINAL RODOVIARIO ) 16:30 | UBERABA - MG ( TERMINAL RODOVIARIO ) 18:45 | BARRETOS - SP ( TERMINAL RODOVIARIO ) 21:45 | SAO JOSE DO RIO PRETO - SP ( TERMINAL RODOVIARIO ) 23:25 | PARAPUA - SP ( TERMINAL RODOVIARIO ) 02:50 | PRESIDENTE PRUDENTE - SP ( TERMINAL RODOVIARIO ) 04:05 | BATAGUASSU - MS ( TERMINAL RODOVIARIO ) 06:05 | NOVA ANDRADINA-NOVA CASA VERDE - MS ( POSTO GABRIELLY ) 07:25 | NOVA ALVORADA DO SUL - MS ( TERMINAL RODOVIARIO ) 09:40 | CAMPO GRANDE - MS ( TERMINAL RODOVIARIO ) 11:25",
        link : "https://wa.me/5567999718063",
        tags : "BRASILIA X CAMPO GRANDE"
    },
    {
        titulo : "BRASILIA X CAMPO GRANDE 06:45",
        descricao : "BRASILIA - DF ( TERMINAL RODOVIARIO ) 06:45 | TAGUATINGA - DF ( TERMINAL RODOVIARIO ) 07:20 | GOIANIA - GO ( TERMINAL RODOVIARIO ) 10:50 | ITUMBIARA - GO ( TERMINAL RODOVIARIO ) 14:30 | UBERLÂNDIA - MG ( TERMINAL RODOVIARIO ) 16:35 | PRATA - MG ( TERMINAL RODOVIARIO ) 18:05 | FRUTAL - MG ( TERMINAL RODOVIARIO ) 20:15 | FRONTEIRA - MG ( TERMINAL RODOVIARIO ) 21:10 | SAO JOSE DO RIO PRETO - SP ( TERMINAL RODOVIARIO ) 22:15 | JOSE BONIFACIO - SP ( TERMINAL RODOVIARIO ) 23:55 | BIRIGUI - SP ( TERMINAL RODOVIARIO ) 01:20 | ARACATUBA - SP ( TERMINAL RODOVIARIO ) 01:45 | TRES LAGOAS - MS ( TERMINAL RODOVIARIO ) 03:05 | AGUA CLARA - MS ( TERMINAL RODOVIARIO ) 05:50 | RIBAS DO RIO PARDO - MS ( TERMINAL RODOVIARIO ) 07:15 | CAMPO GRANDE - MS ( TERMINAL RODOVIARIO ) 08:50",
        link : "https://wa.me/5567999718063",
        tags : "BRASILIA X CAMPO GRANDE"
    },
    {
        titulo : "CAMPO GRANDE X BRASILIA 21:15",
        descricao : "CAMPO GRANDE - MS ( TERMINAL RODOVIARIO ) 21:15 | RIBAS DO RIO PARDO - MS ( TERMINAL RODOVIARIO ) 22:35 | AGUA CLARA - MS ( TERMINAL RODOVIARIO ) 00:00 | TRES LAGOAS - MS ( TERMINAL RODOVIARIO ) 02:40 | ANDRADINA - SP ( TERMINAL RODOVIARIO ) 04:40 | ARACATUBA - SP ( TERMINAL RODOVIARIO ) 06:05 | BIRIGUI - SP ( TERMINAL RODOVIARIO ) 06:30 | PENAPOLIS - SP ( TERMINAL RODOVIARIO ) 07:15 | JOSE BONIFACIO - SP ( TERMINAL RODOVIARIO ) 08:20 | SAO JOSE DO RIO PRETO - SP ( TERMINAL RODOVIARIO ) 09:15 | FRONTEIRA - MG ( TERMINAL RODOVIARIO ) 11:10 | FRUTAL - MG ( TERMINAL RODOVIARIO ) 12:05 | PRATA - MG ( TERMINAL RODOVIARIO ) 14:15 | UBERLÂNDIA - MG ( TERMINAL RODOVIARIO ) 15:35 | ARAGUARI - MG ( TERMINAL RODOVIARIO ) 16:25 | CATALAO - GO ( TERMINAL RODOVIARIO ) 17:40 | CRISTALINA - GO ( TERMINAL RODOVIARIO ) 19:55 | VALPARAÍSO DE GOIÁS - GO 21:15 | BRASILIA - DF ( TERMINAL RODOVIARIO ) 22:00",
        link : "https://wa.me/5567999718063",
        tags : "CAMPO GRANDE X BRASILIA"
    },
    {
        titulo : "BELO HORIZONTE X PRESIDENTE PRUDENTE 21:15",
        descricao : "BELO HORIZONTE - MG ( TERMINAL RODOVIARIO ) 20:30 | BETIM - MG ( TERMINAL RODOVIARIO ) 21:00 | ITAUNA - MG ( TERMINAL RODOVIARIO ) 21:55 | DIVINOPOLIS - MG ( TERMINAL RODOVIARIO ) 22:35 | POSTO MAR DE MINAS - MG 23:55 | PIUMHI - MG ( TERMINAL RODOVIARIO ) 01:25 | PASSOS - MG ( TERMINAL RODOVIARIO ) 02:50 | SAO SEBASTIAO DO PARAISO - MG ( TERMINAL RODOVIARIO ) 03:45 | RIBEIRÃO PRETO - SP ( TERMINAL RODOVIARIO ) 05:30 | SAO CARLOS - SP ( TERMINAL RODOVIARIO ) 08:00 | ARARAQUARA - SP ( TERMINAL RODOVIARIO ) 08:55 | JAU - SP ( TERMINAL RODOVIARIO ) 10:15 | BAURU - SP ( TERMINAL RODOVIARIO ) 12:05 | MARILIA - SP ( TERMINAL RODOVIARIO ) 13:45 | ASSIS - SP ( TERMINAL RODOVIARIO ) 15:05 | PRESIDENTE PRUDENTE - SP ( TERMINAL RODOVIARIO ) 16:45",
        link : "https://wa.me/5567999718063",
        tags : "BELO HORIZONTE X PRESIDENTE PRUDENTE"
    },
   {
        titulo : "DOURADOS X PRESIDENTE PRUDENTE 09:45",
        descricao : "DOURADOS - MS ( TERMINAL RODOVIARIO ) 09:45 | VILA S PEDRO - MS ( TERMINAL RODOVIARIO ) 09:56 | INDAPOLIS - MS 10:05 | FATIMA DO SUL - MS ( TERMINAL RODOVIARIO ) 10:35 | VICENTINA - MS ( TERMINAL RODOVIARIO ) 10:45 | GLORIA DE DOURADOS - MS ( TERMINAL RODOVIARIO ) 11:25 | DEODAPOLIS - MS ( TERMINAL RODOVIARIO ) 11:50 | FAZ HELIO PEREIRA - MS 12:04 | IVINHEMA - MS ( TERMINAL RODOVIARIO ) 12:45 | VILA ALICE - MS 12:58 | AMANDINA - MS ( TERMINAL RODOVIARIO ) 13:15 | BERNARDES - MS ( TERMINAL RODOVIARIO ) 13:31 | NOVA ANDRADINA - MS ( TERMINAL RODOVIARIO ) 14:00 | BATAYPORA - MS ( TERMINAL RODOVIARIO ) 14:20 | FAZ CONQUISTA - MS 14:39 | FAZ BOA VISTA - MS 14:58 | CORREGO TRES BARRAS (ANAURILANDIA) - MS 15:06 | USINA AURORA - MS 15:11 | FAZ VISTA ALEGRE - MS 15:19 | ANAURILANDIA - MS ( TERMINAL RODOVIARIO ) 15:45 | FAZ BANDEIRANTES - MS 15:58 | QUEBRACHO - MS 16:15 | FAZ S JOSE - MS 16:26 | FAZ STA ROSA - MS 16:37 | BATAGUASSU - MS ( TERMINAL RODOVIARIO ) 16:45 | RETA V - MS 16:53 | RETA 1 - MS 16:59 | NOVA PORTO XV DE NOVEMBRO - MS 17:09 | PRESIDENTE EPITACIO - SP ( TERMINAL RODOVIARIO ) 18:20 | PRESIDENTE VENCESLAU - SP ( TERMINAL RODOVIARIO ) 19:05 | SANTO ANASTACIO - SP ( TERMINAL RODOVIARIO ) 19:35 | PRESIDENTE BERNARDES - SP ( TERMINAL RODOVIARIO ) 19:50 | PRESIDENTE PRUDENTE - SP ( TERMINAL RODOVIARIO ) 20:05",
        link : "https://wa.me/5567999718063",
        tags : " DOURADOS X PRESIDENTE PRUDENTE"
    },
   {
        titulo : "DOURADOS X SÃO PAULO 16:00",
        descricao : " DOURADOS - MS ( TERMINAL RODOVIARIO ) 16:00 | FATIMA DO SUL - MS ( TERMINAL RODOVIARIO ) 16:40 | GLORIA DE DOURADOS - MS ( TERMINAL RODOVIARIO ) 17:20 | DEODAPOLIS - MS ( TERMINAL RODOVIARIO ) 17:45 | IVINHEMA - MS ( TERMINAL RODOVIARIO ) 18:25 | AMANDINA - MS ( TERMINAL RODOVIARIO ) 18:55 | NOVA ANDRADINA - MS ( TERMINAL RODOVIARIO ) 19:15 | BATAYPORA - MS ( TERMINAL RODOVIARIO ) 19:35 | ANAURILANDIA - MS ( TERMINAL RODOVIARIO ) 21:00 | BATAGUASSU - MS ( TERMINAL RODOVIARIO ) 22:30 | PRESIDENTE PRUDENTE - SP ( TERMINAL RODOVIARIO ) 01:15 | GRAAL MARISTELA - SP 07:00 | OSASCO - SP ( TERMINAL RODOVIARIO ) 08:35 | SAO PAULO - SP ( TERMINAL RODOVIARIO BARRA FUNDA ) 10:00",
        link : "https://wa.me/5567999718063",
        tags : " DOURADOS X SÃO PAULO"
    },
   {
        titulo : "NAVIRAI X CAMPO GRANDE 16:40",
        descricao : "NAVIRAI - MS ( TERMINAL RODOVIARIO ) 16:40 | FIGUEIRA (NAVIRAI) - MS 17:00 | ESTRADA NOVA - MS ( TERMINAL RODOVIARIO ) 17:08 | FAZ STA JOSEFA - MS 17:15 | PONTE RIO GUIRAI - MS 17:28 | ENT MS 141/MS 475 (SERRARIA) - MS 17:36 | AC GLEBA MARAU - MS 17:47 | ESC GLEBA NOVA - MS 17:55 | AC FAZ SOMECO - MS 18:03 | IVINHEMA - MS ( TERMINAL RODOVIARIO ) 18:17 | VILA ALICE - MS 18:29 | AMANDINA - MS ( TERMINAL RODOVIARIO ) 18:40 | PONTE RIO IVINHEMA - MS 18:47 | BERNARDES - MS ( TERMINAL RODOVIARIO ) 18:56 | AC TAQUARUSSU - MS ( TERMINAL RODOVIARIO ) 19:03 | NOVA ANDRADINA - MS ( TERMINAL RODOVIARIO ) 19:10 | TIMBORE - MS ( TERMINAL RODOVIARIO ) 19:28 | XAVANTES - MS 19:41 | GLEBA ANGICO - MS 19:54 | NOVA ANDRADINA-NOVA CASA VERDE - MS ( POSTO GABRIELLY ) 20:35 | ENT MS 267/141 (VICTOR) - MS 20:52 | POSTO PRIMAVERA - MS 21:27 | POSTO GAUCHAO - MS 21:35 | ENT BR/267/145 - MS 21:40 | POSTO KM 210 - MS 22:00 | ZUZU - MS 22:12 | NOVA ALVORADA DO SUL - MS ( TERMINAL RODOVIARIO ) 22:37 | ANHANDUI - MS ( TERMINAL RODOVIARIO ) 23:19 | CAMPO GRANDE - MS ( TERMINAL RODOVIARIO ) 23:59",
        link : "https://wa.me/5567999718063",
        tags : "NAVIRAI X CAMPO GRANDE"
    },
   {
        titulo : " CAMPO GRANDE X NAVIRAI 08:00",
        descricao : " CAMPO GRANDE - MS ( TERMINAL RODOVIARIO ) 08:00 | ANHANDUI - MS ( TERMINAL RODOVIARIO ) 08:48 | NOVA ALVORADA DO SUL - MS ( TERMINAL RODOVIARIO ) 09:33 | ZUZU - MS 09:55 | POSTO KM 210 - MS 10:07 | ENT BR/267/145 - MS 10:27 | POSTO GAUCHAO - MS 10:32 | POSTO PRIMAVERA - MS 10:40 | ENT MS 267/141 (VICTOR) - MS 11:15 | NOVA ANDRADINA-NOVA CASA VERDE - MS ( POSTO GABRIELLY ) 12:00 | GLEBA ANGICO - MS 12:13 | XAVANTES - MS 12:26 | TIMBORE - MS ( TERMINAL RODOVIARIO ) 12:39 | NOVA ANDRADINA - MS ( TERMINAL RODOVIARIO ) 12:55 | AC TAQUARUSSU - MS ( TERMINAL RODOVIARIO ) 13:04 | BERNARDES - MS ( TERMINAL RODOVIARIO ) 13:11 | PONTE RIO IVINHEMA - MS 13:20 | AMANDINA - MS ( TERMINAL RODOVIARIO ) 13:27 | VILA ALICE - MS 13:38 | IVINHEMA - MS ( TERMINAL RODOVIARIO ) 13:53 | AC FAZ SOMECO - MS 14:04 | ESC GLEBA NOVA - MS 14:12 | AC GLEBA MARAU - MS 14:20 | ENT MS 141/MS 475 (SERRARIA) - MS 14:31 | PONTE RIO GUIRAI - MS 14:39 | FAZ STA JOSEFA - MS 14:52 | ESTRADA NOVA - MS ( TERMINAL RODOVIARIO ) 14:59 | FIGUEIRA (NAVIRAI) - MS 15:07 |NAVIRAI - MS ( TERMINAL RODOVIARIO ) 15:25",
        link : "https://wa.me/5567999718063",
        tags : " CAMPO GRANDE  X NAVIRAI"
    },
];
